//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.EditorialWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="EditorialWS.EditorialWS")]
    public interface EditorialWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/obtenerEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/obtenerEditorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.EditorialWS.obtenerEditorialResponse obtenerEditorial(CampusStoreWeb.EditorialWS.obtenerEditorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/obtenerEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/obtenerEditorialResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.obtenerEditorialResponse> obtenerEditorialAsync(CampusStoreWeb.EditorialWS.obtenerEditorialRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/eliminarEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/eliminarEditorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.EditorialWS.eliminarEditorialResponse eliminarEditorial(CampusStoreWeb.EditorialWS.eliminarEditorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/eliminarEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/eliminarEditorialResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.eliminarEditorialResponse> eliminarEditorialAsync(CampusStoreWeb.EditorialWS.eliminarEditorialRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/listarEditorialesRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/listarEditorialesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.EditorialWS.listarEditorialesResponse listarEditoriales(CampusStoreWeb.EditorialWS.listarEditorialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/listarEditorialesRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/listarEditorialesResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.listarEditorialesResponse> listarEditorialesAsync(CampusStoreWeb.EditorialWS.listarEditorialesRequest request);
        
        // CODEGEN: El parámetro 'editorial' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/guardarEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/guardarEditorialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.EditorialWS.guardarEditorialResponse guardarEditorial(CampusStoreWeb.EditorialWS.guardarEditorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/EditorialWS/guardarEditorialRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/EditorialWS/guardarEditorialResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.guardarEditorialResponse> guardarEditorialAsync(CampusStoreWeb.EditorialWS.guardarEditorialRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class editorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cifField;
        
        private string direccionField;
        
        private string emailField;
        
        private int idEditorialField;
        
        private bool idEditorialFieldSpecified;
        
        private string nombreField;
        
        private string sitioWebField;
        
        private int telefonoField;
        
        private bool telefonoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cif {
            get {
                return this.cifField;
            }
            set {
                this.cifField = value;
                this.RaisePropertyChanged("cif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEditorialSpecified {
            get {
                return this.idEditorialFieldSpecified;
            }
            set {
                this.idEditorialFieldSpecified = value;
                this.RaisePropertyChanged("idEditorialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sitioWeb {
            get {
                return this.sitioWebField;
            }
            set {
                this.sitioWebField = value;
                this.RaisePropertyChanged("sitioWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("telefonoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEditorial", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEditorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerEditorialRequest() {
        }
        
        public obtenerEditorialRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEditorialResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEditorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.EditorialWS.editorial @return;
        
        public obtenerEditorialResponse() {
        }
        
        public obtenerEditorialResponse(CampusStoreWeb.EditorialWS.editorial @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEditorial", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEditorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarEditorialRequest() {
        }
        
        public eliminarEditorialRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEditorialResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEditorialResponse {
        
        public eliminarEditorialResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEditoriales", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEditorialesRequest {
        
        public listarEditorialesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEditorialesResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEditorialesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.EditorialWS.editorial[] @return;
        
        public listarEditorialesResponse() {
        }
        
        public listarEditorialesResponse(CampusStoreWeb.EditorialWS.editorial[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEditorial", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEditorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.EditorialWS.editorial editorial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.EditorialWS.estado estado;
        
        public guardarEditorialRequest() {
        }
        
        public guardarEditorialRequest(CampusStoreWeb.EditorialWS.editorial editorial, CampusStoreWeb.EditorialWS.estado estado) {
            this.editorial = editorial;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarEditorialResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarEditorialResponse {
        
        public guardarEditorialResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EditorialWSChannel : CampusStoreWeb.EditorialWS.EditorialWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditorialWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.EditorialWS.EditorialWS>, CampusStoreWeb.EditorialWS.EditorialWS {
        
        public EditorialWSClient() {
        }
        
        public EditorialWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EditorialWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditorialWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EditorialWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.EditorialWS.obtenerEditorialResponse CampusStoreWeb.EditorialWS.EditorialWS.obtenerEditorial(CampusStoreWeb.EditorialWS.obtenerEditorialRequest request) {
            return base.Channel.obtenerEditorial(request);
        }
        
        public CampusStoreWeb.EditorialWS.editorial obtenerEditorial(int id) {
            CampusStoreWeb.EditorialWS.obtenerEditorialRequest inValue = new CampusStoreWeb.EditorialWS.obtenerEditorialRequest();
            inValue.id = id;
            CampusStoreWeb.EditorialWS.obtenerEditorialResponse retVal = ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).obtenerEditorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.obtenerEditorialResponse> CampusStoreWeb.EditorialWS.EditorialWS.obtenerEditorialAsync(CampusStoreWeb.EditorialWS.obtenerEditorialRequest request) {
            return base.Channel.obtenerEditorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.obtenerEditorialResponse> obtenerEditorialAsync(int id) {
            CampusStoreWeb.EditorialWS.obtenerEditorialRequest inValue = new CampusStoreWeb.EditorialWS.obtenerEditorialRequest();
            inValue.id = id;
            return ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).obtenerEditorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.EditorialWS.eliminarEditorialResponse CampusStoreWeb.EditorialWS.EditorialWS.eliminarEditorial(CampusStoreWeb.EditorialWS.eliminarEditorialRequest request) {
            return base.Channel.eliminarEditorial(request);
        }
        
        public void eliminarEditorial(int id) {
            CampusStoreWeb.EditorialWS.eliminarEditorialRequest inValue = new CampusStoreWeb.EditorialWS.eliminarEditorialRequest();
            inValue.id = id;
            CampusStoreWeb.EditorialWS.eliminarEditorialResponse retVal = ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).eliminarEditorial(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.eliminarEditorialResponse> CampusStoreWeb.EditorialWS.EditorialWS.eliminarEditorialAsync(CampusStoreWeb.EditorialWS.eliminarEditorialRequest request) {
            return base.Channel.eliminarEditorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.eliminarEditorialResponse> eliminarEditorialAsync(int id) {
            CampusStoreWeb.EditorialWS.eliminarEditorialRequest inValue = new CampusStoreWeb.EditorialWS.eliminarEditorialRequest();
            inValue.id = id;
            return ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).eliminarEditorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.EditorialWS.listarEditorialesResponse CampusStoreWeb.EditorialWS.EditorialWS.listarEditoriales(CampusStoreWeb.EditorialWS.listarEditorialesRequest request) {
            return base.Channel.listarEditoriales(request);
        }
        
        public CampusStoreWeb.EditorialWS.editorial[] listarEditoriales() {
            CampusStoreWeb.EditorialWS.listarEditorialesRequest inValue = new CampusStoreWeb.EditorialWS.listarEditorialesRequest();
            CampusStoreWeb.EditorialWS.listarEditorialesResponse retVal = ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).listarEditoriales(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.listarEditorialesResponse> CampusStoreWeb.EditorialWS.EditorialWS.listarEditorialesAsync(CampusStoreWeb.EditorialWS.listarEditorialesRequest request) {
            return base.Channel.listarEditorialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.listarEditorialesResponse> listarEditorialesAsync() {
            CampusStoreWeb.EditorialWS.listarEditorialesRequest inValue = new CampusStoreWeb.EditorialWS.listarEditorialesRequest();
            return ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).listarEditorialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.EditorialWS.guardarEditorialResponse CampusStoreWeb.EditorialWS.EditorialWS.guardarEditorial(CampusStoreWeb.EditorialWS.guardarEditorialRequest request) {
            return base.Channel.guardarEditorial(request);
        }
        
        public void guardarEditorial(CampusStoreWeb.EditorialWS.editorial editorial, CampusStoreWeb.EditorialWS.estado estado) {
            CampusStoreWeb.EditorialWS.guardarEditorialRequest inValue = new CampusStoreWeb.EditorialWS.guardarEditorialRequest();
            inValue.editorial = editorial;
            inValue.estado = estado;
            CampusStoreWeb.EditorialWS.guardarEditorialResponse retVal = ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).guardarEditorial(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.guardarEditorialResponse> CampusStoreWeb.EditorialWS.EditorialWS.guardarEditorialAsync(CampusStoreWeb.EditorialWS.guardarEditorialRequest request) {
            return base.Channel.guardarEditorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.EditorialWS.guardarEditorialResponse> guardarEditorialAsync(CampusStoreWeb.EditorialWS.editorial editorial, CampusStoreWeb.EditorialWS.estado estado) {
            CampusStoreWeb.EditorialWS.guardarEditorialRequest inValue = new CampusStoreWeb.EditorialWS.guardarEditorialRequest();
            inValue.editorial = editorial;
            inValue.estado = estado;
            return ((CampusStoreWeb.EditorialWS.EditorialWS)(this)).guardarEditorialAsync(inValue);
        }
    }
}
