//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.FiltroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="FiltroWS.FiltroWS")]
    public interface FiltroWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarPorTipoArticuloRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarPorTipoArticuloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse filtrarPorTipoArticulo(CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarPorTipoArticuloRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarPorTipoArticuloResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse> filtrarPorTipoArticuloAsync(CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarLibrosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarLibrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.FiltroWS.filtrarLibrosResponse filtrarLibros(CampusStoreWeb.FiltroWS.filtrarLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarLibrosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/FiltroWS/filtrarLibrosResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarLibrosResponse> filtrarLibrosAsync(CampusStoreWeb.FiltroWS.filtrarLibrosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class articulo : producto {
        
        private int idArticuloField;
        
        private bool idArticuloFieldSpecified;
        
        private tipoArticulo tipoArticuloField;
        
        private bool tipoArticuloFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
                this.RaisePropertyChanged("idArticulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idArticuloSpecified {
            get {
                return this.idArticuloFieldSpecified;
            }
            set {
                this.idArticuloFieldSpecified = value;
                this.RaisePropertyChanged("idArticuloSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoArticulo tipoArticulo {
            get {
                return this.tipoArticuloField;
            }
            set {
                this.tipoArticuloField = value;
                this.RaisePropertyChanged("tipoArticulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoArticuloSpecified {
            get {
                return this.tipoArticuloFieldSpecified;
            }
            set {
                this.tipoArticuloFieldSpecified = value;
                this.RaisePropertyChanged("tipoArticuloSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoArticulo {
        
        /// <remarks/>
        LAPICERO,
        
        /// <remarks/>
        CUADERNO,
        
        /// <remarks/>
        PELUCHE,
        
        /// <remarks/>
        TOMATODO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(articulo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(libro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private descuento descuentoField;
        
        private string imagenURLField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private double precioDescuentoField;
        
        private bool precioDescuentoFieldSpecified;
        
        private reseña[] reseñasField;
        
        private int stockRealField;
        
        private bool stockRealFieldSpecified;
        
        private int stockVirtualField;
        
        private bool stockVirtualFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public descuento descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("imagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioDescuento {
            get {
                return this.precioDescuentoField;
            }
            set {
                this.precioDescuentoField = value;
                this.RaisePropertyChanged("precioDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioDescuentoSpecified {
            get {
                return this.precioDescuentoFieldSpecified;
            }
            set {
                this.precioDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("precioDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseñas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public reseña[] reseñas {
            get {
                return this.reseñasField;
            }
            set {
                this.reseñasField = value;
                this.RaisePropertyChanged("reseñas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockReal {
            get {
                return this.stockRealField;
            }
            set {
                this.stockRealField = value;
                this.RaisePropertyChanged("stockReal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockRealSpecified {
            get {
                return this.stockRealFieldSpecified;
            }
            set {
                this.stockRealFieldSpecified = value;
                this.RaisePropertyChanged("stockRealSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockVirtual {
            get {
                return this.stockVirtualField;
            }
            set {
                this.stockVirtualField = value;
                this.RaisePropertyChanged("stockVirtual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockVirtualSpecified {
            get {
                return this.stockVirtualFieldSpecified;
            }
            set {
                this.stockVirtualFieldSpecified = value;
                this.RaisePropertyChanged("stockVirtualSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idDescuentoField;
        
        private bool idDescuentoFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        private double valorDescuentoField;
        
        private bool valorDescuentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDescuentoSpecified {
            get {
                return this.idDescuentoFieldSpecified;
            }
            set {
                this.idDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("idDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double valorDescuento {
            get {
                return this.valorDescuentoField;
            }
            set {
                this.valorDescuentoField = value;
                this.RaisePropertyChanged("valorDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDescuentoSpecified {
            get {
                return this.valorDescuentoFieldSpecified;
            }
            set {
                this.valorDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("valorDescuentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoProducto {
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        LIBRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class editorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cifField;
        
        private string direccionField;
        
        private string emailField;
        
        private int idEditorialField;
        
        private bool idEditorialFieldSpecified;
        
        private string nombreField;
        
        private string sitioWebField;
        
        private int telefonoField;
        
        private bool telefonoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cif {
            get {
                return this.cifField;
            }
            set {
                this.cifField = value;
                this.RaisePropertyChanged("cif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEditorialSpecified {
            get {
                return this.idEditorialFieldSpecified;
            }
            set {
                this.idEditorialFieldSpecified = value;
                this.RaisePropertyChanged("idEditorialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sitioWeb {
            get {
                return this.sitioWebField;
            }
            set {
                this.sitioWebField = value;
                this.RaisePropertyChanged("sitioWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("telefonoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private string apellidosField;
        
        private int idAutorField;
        
        private bool idAutorFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAutorSpecified {
            get {
                return this.idAutorFieldSpecified;
            }
            set {
                this.idAutorFieldSpecified = value;
                this.RaisePropertyChanged("idAutorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string codigoField;
        
        private double descuentoField;
        
        private bool descuentoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idCuponField;
        
        private bool idCuponFieldSpecified;
        
        private int usosRestantesField;
        
        private bool usosRestantesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoSpecified {
            get {
                return this.descuentoFieldSpecified;
            }
            set {
                this.descuentoFieldSpecified = value;
                this.RaisePropertyChanged("descuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCupon {
            get {
                return this.idCuponField;
            }
            set {
                this.idCuponField = value;
                this.RaisePropertyChanged("idCupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCuponSpecified {
            get {
                return this.idCuponFieldSpecified;
            }
            set {
                this.idCuponFieldSpecified = value;
                this.RaisePropertyChanged("idCuponSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int usosRestantes {
            get {
                return this.usosRestantesField;
            }
            set {
                this.usosRestantesField = value;
                this.RaisePropertyChanged("usosRestantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usosRestantesSpecified {
            get {
                return this.usosRestantesFieldSpecified;
            }
            set {
                this.usosRestantesFieldSpecified = value;
                this.RaisePropertyChanged("usosRestantesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cliente : usuario {
        
        private cupon[] cuponesUsadosField;
        
        private int idClienteField;
        
        private bool idClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuponesUsados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cupon[] cuponesUsados {
            get {
                return this.cuponesUsadosField;
            }
            set {
                this.cuponesUsadosField = value;
                this.RaisePropertyChanged("cuponesUsados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class reseña : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double calificacionField;
        
        private cliente clienteField;
        
        private int idReseñaField;
        
        private bool idReseñaFieldSpecified;
        
        private producto productoField;
        
        private string reseña1Field;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                this.calificacionField = value;
                this.RaisePropertyChanged("calificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idReseña {
            get {
                return this.idReseñaField;
            }
            set {
                this.idReseñaField = value;
                this.RaisePropertyChanged("idReseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idReseñaSpecified {
            get {
                return this.idReseñaFieldSpecified;
            }
            set {
                this.idReseñaFieldSpecified = value;
                this.RaisePropertyChanged("idReseñaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseña", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reseña1 {
            get {
                return this.reseña1Field;
            }
            set {
                this.reseña1Field = value;
                this.RaisePropertyChanged("reseña1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class libro : producto {
        
        private autor[] autoresField;
        
        private editorial editorialField;
        
        private System.DateTime fechaPublicacionField;
        
        private bool fechaPublicacionFieldSpecified;
        
        private formato formatoField;
        
        private bool formatoFieldSpecified;
        
        private generoLibro generoField;
        
        private bool generoFieldSpecified;
        
        private int idLibroField;
        
        private bool idLibroFieldSpecified;
        
        private string isbnField;
        
        private string sinopsisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("autores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public autor[] autores {
            get {
                return this.autoresField;
            }
            set {
                this.autoresField = value;
                this.RaisePropertyChanged("autores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public editorial editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("fechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPublicacionSpecified {
            get {
                return this.fechaPublicacionFieldSpecified;
            }
            set {
                this.fechaPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public formato formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
                this.RaisePropertyChanged("formato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatoSpecified {
            get {
                return this.formatoFieldSpecified;
            }
            set {
                this.formatoFieldSpecified = value;
                this.RaisePropertyChanged("formatoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public generoLibro genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idLibro {
            get {
                return this.idLibroField;
            }
            set {
                this.idLibroField = value;
                this.RaisePropertyChanged("idLibro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLibroSpecified {
            get {
                return this.idLibroFieldSpecified;
            }
            set {
                this.idLibroFieldSpecified = value;
                this.RaisePropertyChanged("idLibroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                this.sinopsisField = value;
                this.RaisePropertyChanged("sinopsis");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum formato {
        
        /// <remarks/>
        TAPA_BLANDA,
        
        /// <remarks/>
        TAPA_DURA,
        
        /// <remarks/>
        COLECCIONISTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum generoLibro {
        
        /// <remarks/>
        DRAMA,
        
        /// <remarks/>
        FANTASIA,
        
        /// <remarks/>
        NOVELA,
        
        /// <remarks/>
        NARRATIVO,
        
        /// <remarks/>
        AVENTURA,
        
        /// <remarks/>
        CIENCIA_FICCION,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarPorTipoArticulo", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarPorTipoArticuloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoArticulo;
        
        public filtrarPorTipoArticuloRequest() {
        }
        
        public filtrarPorTipoArticuloRequest(string tipoArticulo) {
            this.tipoArticulo = tipoArticulo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarPorTipoArticuloResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarPorTipoArticuloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.FiltroWS.articulo[] @return;
        
        public filtrarPorTipoArticuloResponse() {
        }
        
        public filtrarPorTipoArticuloResponse(CampusStoreWeb.FiltroWS.articulo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarLibros", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarLibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("autores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] autores;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("editoriales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] editoriales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("genero", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] genero;
        
        public filtrarLibrosRequest() {
        }
        
        public filtrarLibrosRequest(int[] autores, int[] editoriales, string[] genero) {
            this.autores = autores;
            this.editoriales = editoriales;
            this.genero = genero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarLibrosResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class filtrarLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.FiltroWS.libro[] @return;
        
        public filtrarLibrosResponse() {
        }
        
        public filtrarLibrosResponse(CampusStoreWeb.FiltroWS.libro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiltroWSChannel : CampusStoreWeb.FiltroWS.FiltroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiltroWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.FiltroWS.FiltroWS>, CampusStoreWeb.FiltroWS.FiltroWS {
        
        public FiltroWSClient() {
        }
        
        public FiltroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiltroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiltroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiltroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse CampusStoreWeb.FiltroWS.FiltroWS.filtrarPorTipoArticulo(CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest request) {
            return base.Channel.filtrarPorTipoArticulo(request);
        }
        
        public CampusStoreWeb.FiltroWS.articulo[] filtrarPorTipoArticulo(string tipoArticulo) {
            CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest inValue = new CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest();
            inValue.tipoArticulo = tipoArticulo;
            CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse retVal = ((CampusStoreWeb.FiltroWS.FiltroWS)(this)).filtrarPorTipoArticulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse> CampusStoreWeb.FiltroWS.FiltroWS.filtrarPorTipoArticuloAsync(CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest request) {
            return base.Channel.filtrarPorTipoArticuloAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloResponse> filtrarPorTipoArticuloAsync(string tipoArticulo) {
            CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest inValue = new CampusStoreWeb.FiltroWS.filtrarPorTipoArticuloRequest();
            inValue.tipoArticulo = tipoArticulo;
            return ((CampusStoreWeb.FiltroWS.FiltroWS)(this)).filtrarPorTipoArticuloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.FiltroWS.filtrarLibrosResponse CampusStoreWeb.FiltroWS.FiltroWS.filtrarLibros(CampusStoreWeb.FiltroWS.filtrarLibrosRequest request) {
            return base.Channel.filtrarLibros(request);
        }
        
        public CampusStoreWeb.FiltroWS.libro[] filtrarLibros(int[] autores, int[] editoriales, string[] genero) {
            CampusStoreWeb.FiltroWS.filtrarLibrosRequest inValue = new CampusStoreWeb.FiltroWS.filtrarLibrosRequest();
            inValue.autores = autores;
            inValue.editoriales = editoriales;
            inValue.genero = genero;
            CampusStoreWeb.FiltroWS.filtrarLibrosResponse retVal = ((CampusStoreWeb.FiltroWS.FiltroWS)(this)).filtrarLibros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarLibrosResponse> CampusStoreWeb.FiltroWS.FiltroWS.filtrarLibrosAsync(CampusStoreWeb.FiltroWS.filtrarLibrosRequest request) {
            return base.Channel.filtrarLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.FiltroWS.filtrarLibrosResponse> filtrarLibrosAsync(int[] autores, int[] editoriales, string[] genero) {
            CampusStoreWeb.FiltroWS.filtrarLibrosRequest inValue = new CampusStoreWeb.FiltroWS.filtrarLibrosRequest();
            inValue.autores = autores;
            inValue.editoriales = editoriales;
            inValue.genero = genero;
            return ((CampusStoreWeb.FiltroWS.FiltroWS)(this)).filtrarLibrosAsync(inValue);
        }
    }
}
