//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.DescuentoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="DescuentoWS.DescuentoWS")]
    public interface DescuentoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/listarDescuentosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/listarDescuentosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.DescuentoWS.listarDescuentosResponse listarDescuentos(CampusStoreWeb.DescuentoWS.listarDescuentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/listarDescuentosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/listarDescuentosResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.listarDescuentosResponse> listarDescuentosAsync(CampusStoreWeb.DescuentoWS.listarDescuentosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse obtenerDescuento(CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse> obtenerDescuentoAsync(CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest request);
        
        // CODEGEN: El parámetro 'descuento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/guardarDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/guardarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.DescuentoWS.guardarDescuentoResponse guardarDescuento(CampusStoreWeb.DescuentoWS.guardarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/guardarDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/guardarDescuentoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.guardarDescuentoResponse> guardarDescuentoAsync(CampusStoreWeb.DescuentoWS.guardarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'descuento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/eliminarDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/eliminarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse eliminarDescuento(CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/eliminarDescuentoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/eliminarDescuentoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse> eliminarDescuentoAsync(CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoPorProductoRe" +
            "quest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoPorProductoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse obtenerDescuentoPorProducto(CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoPorProductoRe" +
            "quest", ReplyAction="http://services.campusstore.pucp.edu.pe/DescuentoWS/obtenerDescuentoPorProductoRe" +
            "sponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse> obtenerDescuentoPorProductoAsync(CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idDescuentoField;
        
        private bool idDescuentoFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        private double valorDescuentoField;
        
        private bool valorDescuentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDescuentoSpecified {
            get {
                return this.idDescuentoFieldSpecified;
            }
            set {
                this.idDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("idDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double valorDescuento {
            get {
                return this.valorDescuentoField;
            }
            set {
                this.valorDescuentoField = value;
                this.RaisePropertyChanged("valorDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDescuentoSpecified {
            get {
                return this.valorDescuentoFieldSpecified;
            }
            set {
                this.valorDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("valorDescuentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoProducto {
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        LIBRO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDescuentos", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDescuentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento descuento;
        
        public listarDescuentosRequest() {
        }
        
        public listarDescuentosRequest(CampusStoreWeb.DescuentoWS.descuento descuento) {
            this.descuento = descuento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDescuentosResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDescuentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento[] @return;
        
        public listarDescuentosResponse() {
        }
        
        public listarDescuentosResponse(CampusStoreWeb.DescuentoWS.descuento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuento", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento descuento;
        
        public obtenerDescuentoRequest() {
        }
        
        public obtenerDescuentoRequest(CampusStoreWeb.DescuentoWS.descuento descuento) {
            this.descuento = descuento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuentoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento @return;
        
        public obtenerDescuentoResponse() {
        }
        
        public obtenerDescuentoResponse(CampusStoreWeb.DescuentoWS.descuento @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarDescuento", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento descuento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.estado estado;
        
        public guardarDescuentoRequest() {
        }
        
        public guardarDescuentoRequest(CampusStoreWeb.DescuentoWS.descuento descuento, CampusStoreWeb.DescuentoWS.estado estado) {
            this.descuento = descuento;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarDescuentoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarDescuentoResponse {
        
        public guardarDescuentoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuento", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento descuento;
        
        public eliminarDescuentoRequest() {
        }
        
        public eliminarDescuentoRequest(CampusStoreWeb.DescuentoWS.descuento descuento) {
            this.descuento = descuento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuentoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoResponse {
        
        public eliminarDescuentoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuentoPorProducto", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoPorProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.tipoProducto tipoProducto;
        
        public obtenerDescuentoPorProductoRequest() {
        }
        
        public obtenerDescuentoPorProductoRequest(int idProducto, CampusStoreWeb.DescuentoWS.tipoProducto tipoProducto) {
            this.idProducto = idProducto;
            this.tipoProducto = tipoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuentoPorProductoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoPorProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.DescuentoWS.descuento @return;
        
        public obtenerDescuentoPorProductoResponse() {
        }
        
        public obtenerDescuentoPorProductoResponse(CampusStoreWeb.DescuentoWS.descuento @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DescuentoWSChannel : CampusStoreWeb.DescuentoWS.DescuentoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DescuentoWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.DescuentoWS.DescuentoWS>, CampusStoreWeb.DescuentoWS.DescuentoWS {
        
        public DescuentoWSClient() {
        }
        
        public DescuentoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DescuentoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.DescuentoWS.listarDescuentosResponse CampusStoreWeb.DescuentoWS.DescuentoWS.listarDescuentos(CampusStoreWeb.DescuentoWS.listarDescuentosRequest request) {
            return base.Channel.listarDescuentos(request);
        }
        
        public CampusStoreWeb.DescuentoWS.descuento[] listarDescuentos(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.listarDescuentosRequest inValue = new CampusStoreWeb.DescuentoWS.listarDescuentosRequest();
            inValue.descuento = descuento;
            CampusStoreWeb.DescuentoWS.listarDescuentosResponse retVal = ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).listarDescuentos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.listarDescuentosResponse> CampusStoreWeb.DescuentoWS.DescuentoWS.listarDescuentosAsync(CampusStoreWeb.DescuentoWS.listarDescuentosRequest request) {
            return base.Channel.listarDescuentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.listarDescuentosResponse> listarDescuentosAsync(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.listarDescuentosRequest inValue = new CampusStoreWeb.DescuentoWS.listarDescuentosRequest();
            inValue.descuento = descuento;
            return ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).listarDescuentosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse CampusStoreWeb.DescuentoWS.DescuentoWS.obtenerDescuento(CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest request) {
            return base.Channel.obtenerDescuento(request);
        }
        
        public CampusStoreWeb.DescuentoWS.descuento obtenerDescuento(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest();
            inValue.descuento = descuento;
            CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse retVal = ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).obtenerDescuento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse> CampusStoreWeb.DescuentoWS.DescuentoWS.obtenerDescuentoAsync(CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest request) {
            return base.Channel.obtenerDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoResponse> obtenerDescuentoAsync(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.obtenerDescuentoRequest();
            inValue.descuento = descuento;
            return ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).obtenerDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.DescuentoWS.guardarDescuentoResponse CampusStoreWeb.DescuentoWS.DescuentoWS.guardarDescuento(CampusStoreWeb.DescuentoWS.guardarDescuentoRequest request) {
            return base.Channel.guardarDescuento(request);
        }
        
        public void guardarDescuento(CampusStoreWeb.DescuentoWS.descuento descuento, CampusStoreWeb.DescuentoWS.estado estado) {
            CampusStoreWeb.DescuentoWS.guardarDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.guardarDescuentoRequest();
            inValue.descuento = descuento;
            inValue.estado = estado;
            CampusStoreWeb.DescuentoWS.guardarDescuentoResponse retVal = ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).guardarDescuento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.guardarDescuentoResponse> CampusStoreWeb.DescuentoWS.DescuentoWS.guardarDescuentoAsync(CampusStoreWeb.DescuentoWS.guardarDescuentoRequest request) {
            return base.Channel.guardarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.guardarDescuentoResponse> guardarDescuentoAsync(CampusStoreWeb.DescuentoWS.descuento descuento, CampusStoreWeb.DescuentoWS.estado estado) {
            CampusStoreWeb.DescuentoWS.guardarDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.guardarDescuentoRequest();
            inValue.descuento = descuento;
            inValue.estado = estado;
            return ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).guardarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse CampusStoreWeb.DescuentoWS.DescuentoWS.eliminarDescuento(CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest request) {
            return base.Channel.eliminarDescuento(request);
        }
        
        public void eliminarDescuento(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest();
            inValue.descuento = descuento;
            CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse retVal = ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).eliminarDescuento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse> CampusStoreWeb.DescuentoWS.DescuentoWS.eliminarDescuentoAsync(CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest request) {
            return base.Channel.eliminarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.eliminarDescuentoResponse> eliminarDescuentoAsync(CampusStoreWeb.DescuentoWS.descuento descuento) {
            CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest inValue = new CampusStoreWeb.DescuentoWS.eliminarDescuentoRequest();
            inValue.descuento = descuento;
            return ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).eliminarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse CampusStoreWeb.DescuentoWS.DescuentoWS.obtenerDescuentoPorProducto(CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest request) {
            return base.Channel.obtenerDescuentoPorProducto(request);
        }
        
        public CampusStoreWeb.DescuentoWS.descuento obtenerDescuentoPorProducto(int idProducto, CampusStoreWeb.DescuentoWS.tipoProducto tipoProducto) {
            CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest inValue = new CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest();
            inValue.idProducto = idProducto;
            inValue.tipoProducto = tipoProducto;
            CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse retVal = ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).obtenerDescuentoPorProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse> CampusStoreWeb.DescuentoWS.DescuentoWS.obtenerDescuentoPorProductoAsync(CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest request) {
            return base.Channel.obtenerDescuentoPorProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoResponse> obtenerDescuentoPorProductoAsync(int idProducto, CampusStoreWeb.DescuentoWS.tipoProducto tipoProducto) {
            CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest inValue = new CampusStoreWeb.DescuentoWS.obtenerDescuentoPorProductoRequest();
            inValue.idProducto = idProducto;
            inValue.tipoProducto = tipoProducto;
            return ((CampusStoreWeb.DescuentoWS.DescuentoWS)(this)).obtenerDescuentoPorProductoAsync(inValue);
        }
    }
}
