//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.OrdenCompraWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="OrdenCompraWS.OrdenCompraWS")]
    public interface OrdenCompraWS {
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse eliminarOrdenCompra(CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraResponse" +
            "")]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse> eliminarOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/listarOrdenesCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/listarOrdenesCompraResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse listarOrdenesCompra(CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/listarOrdenesCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/listarOrdenesCompraResponse" +
            "")]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse> listarOrdenesCompraAsync(CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest request);
        
        // CODEGEN: El parámetro 'ordenCompra' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/guardarOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/guardarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse guardarOrdenCompra(CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/guardarOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/guardarOrdenCompraResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse> guardarOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse obtenerOrdenCompra(CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse> obtenerOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenCompra", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarOrdenCompraRequest() {
        }
        
        public eliminarOrdenCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenCompraResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenCompraResponse {
        
        public eliminarOrdenCompraResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class ordenCompra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private carrito carritoField;
        
        private cliente clienteField;
        
        private estadoOrden estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idOrdenCompraField;
        
        private bool idOrdenCompraFieldSpecified;
        
        private System.DateTime limitePagoField;
        
        private bool limitePagoFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private double totalDescontadoField;
        
        private bool totalDescontadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public carrito carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoOrden estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idOrdenCompra {
            get {
                return this.idOrdenCompraField;
            }
            set {
                this.idOrdenCompraField = value;
                this.RaisePropertyChanged("idOrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOrdenCompraSpecified {
            get {
                return this.idOrdenCompraFieldSpecified;
            }
            set {
                this.idOrdenCompraFieldSpecified = value;
                this.RaisePropertyChanged("idOrdenCompraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime limitePago {
            get {
                return this.limitePagoField;
            }
            set {
                this.limitePagoField = value;
                this.RaisePropertyChanged("limitePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitePagoSpecified {
            get {
                return this.limitePagoFieldSpecified;
            }
            set {
                this.limitePagoFieldSpecified = value;
                this.RaisePropertyChanged("limitePagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double totalDescontado {
            get {
                return this.totalDescontadoField;
            }
            set {
                this.totalDescontadoField = value;
                this.RaisePropertyChanged("totalDescontado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalDescontadoSpecified {
            get {
                return this.totalDescontadoFieldSpecified;
            }
            set {
                this.totalDescontadoFieldSpecified = value;
                this.RaisePropertyChanged("totalDescontadoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class carrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private bool completadoField;
        
        private bool completadoFieldSpecified;
        
        private cupon cuponField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idCarritoField;
        
        private bool idCarritoFieldSpecified;
        
        private lineaCarrito[] lineasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool completado {
            get {
                return this.completadoField;
            }
            set {
                this.completadoField = value;
                this.RaisePropertyChanged("completado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completadoSpecified {
            get {
                return this.completadoFieldSpecified;
            }
            set {
                this.completadoFieldSpecified = value;
                this.RaisePropertyChanged("completadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cupon cupon {
            get {
                return this.cuponField;
            }
            set {
                this.cuponField = value;
                this.RaisePropertyChanged("cupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarritoSpecified {
            get {
                return this.idCarritoFieldSpecified;
            }
            set {
                this.idCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lineaCarrito[] lineas {
            get {
                return this.lineasField;
            }
            set {
                this.lineasField = value;
                this.RaisePropertyChanged("lineas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cliente : usuario {
        
        private cupon[] cuponesUsadosField;
        
        private int idClienteField;
        
        private bool idClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuponesUsados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cupon[] cuponesUsados {
            get {
                return this.cuponesUsadosField;
            }
            set {
                this.cuponesUsadosField = value;
                this.RaisePropertyChanged("cuponesUsados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string codigoField;
        
        private double descuentoField;
        
        private bool descuentoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idCuponField;
        
        private bool idCuponFieldSpecified;
        
        private int usosRestantesField;
        
        private bool usosRestantesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoSpecified {
            get {
                return this.descuentoFieldSpecified;
            }
            set {
                this.descuentoFieldSpecified = value;
                this.RaisePropertyChanged("descuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCupon {
            get {
                return this.idCuponField;
            }
            set {
                this.idCuponField = value;
                this.RaisePropertyChanged("idCupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCuponSpecified {
            get {
                return this.idCuponFieldSpecified;
            }
            set {
                this.idCuponFieldSpecified = value;
                this.RaisePropertyChanged("idCuponSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int usosRestantes {
            get {
                return this.usosRestantesField;
            }
            set {
                this.usosRestantesField = value;
                this.RaisePropertyChanged("usosRestantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usosRestantesSpecified {
            get {
                return this.usosRestantesFieldSpecified;
            }
            set {
                this.usosRestantesFieldSpecified = value;
                this.RaisePropertyChanged("usosRestantesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class reseña : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double calificacionField;
        
        private cliente clienteField;
        
        private int idReseñaField;
        
        private bool idReseñaFieldSpecified;
        
        private producto productoField;
        
        private string reseña1Field;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                this.calificacionField = value;
                this.RaisePropertyChanged("calificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idReseña {
            get {
                return this.idReseñaField;
            }
            set {
                this.idReseñaField = value;
                this.RaisePropertyChanged("idReseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idReseñaSpecified {
            get {
                return this.idReseñaFieldSpecified;
            }
            set {
                this.idReseñaFieldSpecified = value;
                this.RaisePropertyChanged("idReseñaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseña", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reseña1 {
            get {
                return this.reseña1Field;
            }
            set {
                this.reseña1Field = value;
                this.RaisePropertyChanged("reseña1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private descuento descuentoField;
        
        private string imagenURLField;
        
        private string nombreField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private double precioDescuentoField;
        
        private bool precioDescuentoFieldSpecified;
        
        private reseña[] reseñasField;
        
        private int stockRealField;
        
        private bool stockRealFieldSpecified;
        
        private int stockVirtualField;
        
        private bool stockVirtualFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public descuento descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string imagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("imagenURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioDescuento {
            get {
                return this.precioDescuentoField;
            }
            set {
                this.precioDescuentoField = value;
                this.RaisePropertyChanged("precioDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioDescuentoSpecified {
            get {
                return this.precioDescuentoFieldSpecified;
            }
            set {
                this.precioDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("precioDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseñas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public reseña[] reseñas {
            get {
                return this.reseñasField;
            }
            set {
                this.reseñasField = value;
                this.RaisePropertyChanged("reseñas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockReal {
            get {
                return this.stockRealField;
            }
            set {
                this.stockRealField = value;
                this.RaisePropertyChanged("stockReal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockRealSpecified {
            get {
                return this.stockRealFieldSpecified;
            }
            set {
                this.stockRealFieldSpecified = value;
                this.RaisePropertyChanged("stockRealSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockVirtual {
            get {
                return this.stockVirtualField;
            }
            set {
                this.stockVirtualField = value;
                this.RaisePropertyChanged("stockVirtual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockVirtualSpecified {
            get {
                return this.stockVirtualFieldSpecified;
            }
            set {
                this.stockVirtualFieldSpecified = value;
                this.RaisePropertyChanged("stockVirtualSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idDescuentoField;
        
        private bool idDescuentoFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        private double valorDescuentoField;
        
        private bool valorDescuentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDescuentoSpecified {
            get {
                return this.idDescuentoFieldSpecified;
            }
            set {
                this.idDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("idDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double valorDescuento {
            get {
                return this.valorDescuentoField;
            }
            set {
                this.valorDescuentoField = value;
                this.RaisePropertyChanged("valorDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDescuentoSpecified {
            get {
                return this.valorDescuentoFieldSpecified;
            }
            set {
                this.valorDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("valorDescuentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoProducto {
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        LIBRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class lineaCarrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private carrito carritoField;
        
        private int idLineaCarritoField;
        
        private bool idLineaCarritoFieldSpecified;
        
        private double precioConDescuentoField;
        
        private bool precioConDescuentoFieldSpecified;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private producto productoField;
        
        private double subTotalConDescuentoField;
        
        private bool subTotalConDescuentoFieldSpecified;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public carrito carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idLineaCarrito {
            get {
                return this.idLineaCarritoField;
            }
            set {
                this.idLineaCarritoField = value;
                this.RaisePropertyChanged("idLineaCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLineaCarritoSpecified {
            get {
                return this.idLineaCarritoFieldSpecified;
            }
            set {
                this.idLineaCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idLineaCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioConDescuento {
            get {
                return this.precioConDescuentoField;
            }
            set {
                this.precioConDescuentoField = value;
                this.RaisePropertyChanged("precioConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioConDescuentoSpecified {
            get {
                return this.precioConDescuentoFieldSpecified;
            }
            set {
                this.precioConDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("precioConDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double subTotalConDescuento {
            get {
                return this.subTotalConDescuentoField;
            }
            set {
                this.subTotalConDescuentoField = value;
                this.RaisePropertyChanged("subTotalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalConDescuentoSpecified {
            get {
                return this.subTotalConDescuentoFieldSpecified;
            }
            set {
                this.subTotalConDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("subTotalConDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estadoOrden {
        
        /// <remarks/>
        NO_PAGADO,
        
        /// <remarks/>
        PAGADO,
        
        /// <remarks/>
        ENTREGADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesCompra", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesCompraRequest {
        
        public listarOrdenesCompraRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesCompraResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.OrdenCompraWS.ordenCompra[] @return;
        
        public listarOrdenesCompraResponse() {
        }
        
        public listarOrdenesCompraResponse(CampusStoreWeb.OrdenCompraWS.ordenCompra[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrdenCompra", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.OrdenCompraWS.ordenCompra ordenCompra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.OrdenCompraWS.estado estado;
        
        public guardarOrdenCompraRequest() {
        }
        
        public guardarOrdenCompraRequest(CampusStoreWeb.OrdenCompraWS.ordenCompra ordenCompra, CampusStoreWeb.OrdenCompraWS.estado estado) {
            this.ordenCompra = ordenCompra;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarOrdenCompraResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarOrdenCompraResponse {
        
        public guardarOrdenCompraResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenCompra", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerOrdenCompraRequest() {
        }
        
        public obtenerOrdenCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenCompraResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.OrdenCompraWS.ordenCompra @return;
        
        public obtenerOrdenCompraResponse() {
        }
        
        public obtenerOrdenCompraResponse(CampusStoreWeb.OrdenCompraWS.ordenCompra @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenCompraWSChannel : CampusStoreWeb.OrdenCompraWS.OrdenCompraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenCompraWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.OrdenCompraWS.OrdenCompraWS>, CampusStoreWeb.OrdenCompraWS.OrdenCompraWS {
        
        public OrdenCompraWSClient() {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.eliminarOrdenCompra(CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest request) {
            return base.Channel.eliminarOrdenCompra(request);
        }
        
        public void eliminarOrdenCompra(int id) {
            CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest();
            inValue.id = id;
            CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse retVal = ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse> CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.eliminarOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest request) {
            return base.Channel.eliminarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraResponse> eliminarOrdenCompraAsync(int id) {
            CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.eliminarOrdenCompraRequest();
            inValue.id = id;
            return ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.listarOrdenesCompra(CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest request) {
            return base.Channel.listarOrdenesCompra(request);
        }
        
        public CampusStoreWeb.OrdenCompraWS.ordenCompra[] listarOrdenesCompra() {
            CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest();
            CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse retVal = ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).listarOrdenesCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse> CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.listarOrdenesCompraAsync(CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest request) {
            return base.Channel.listarOrdenesCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraResponse> listarOrdenesCompraAsync() {
            CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.listarOrdenesCompraRequest();
            return ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).listarOrdenesCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.guardarOrdenCompra(CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest request) {
            return base.Channel.guardarOrdenCompra(request);
        }
        
        public void guardarOrdenCompra(CampusStoreWeb.OrdenCompraWS.ordenCompra ordenCompra, CampusStoreWeb.OrdenCompraWS.estado estado) {
            CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            inValue.estado = estado;
            CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse retVal = ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).guardarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse> CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.guardarOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest request) {
            return base.Channel.guardarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraResponse> guardarOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.ordenCompra ordenCompra, CampusStoreWeb.OrdenCompraWS.estado estado) {
            CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.guardarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            inValue.estado = estado;
            return ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).guardarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.obtenerOrdenCompra(CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest request) {
            return base.Channel.obtenerOrdenCompra(request);
        }
        
        public CampusStoreWeb.OrdenCompraWS.ordenCompra obtenerOrdenCompra(int id) {
            CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest();
            inValue.id = id;
            CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse retVal = ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse> CampusStoreWeb.OrdenCompraWS.OrdenCompraWS.obtenerOrdenCompraAsync(CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest request) {
            return base.Channel.obtenerOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraResponse> obtenerOrdenCompraAsync(int id) {
            CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest inValue = new CampusStoreWeb.OrdenCompraWS.obtenerOrdenCompraRequest();
            inValue.id = id;
            return ((CampusStoreWeb.OrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenCompraAsync(inValue);
        }
    }
}
