//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.AutorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="AutorWS.AutorWS")]
    public interface AutorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/obtenerAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/obtenerAutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.AutorWS.obtenerAutorResponse obtenerAutor(CampusStoreWeb.AutorWS.obtenerAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/obtenerAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/obtenerAutorResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.obtenerAutorResponse> obtenerAutorAsync(CampusStoreWeb.AutorWS.obtenerAutorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/listarAutoresRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/listarAutoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.AutorWS.listarAutoresResponse listarAutores(CampusStoreWeb.AutorWS.listarAutoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/listarAutoresRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/listarAutoresResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.listarAutoresResponse> listarAutoresAsync(CampusStoreWeb.AutorWS.listarAutoresRequest request);
        
        // CODEGEN: El parámetro 'autor' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/guardarAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/guardarAutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.AutorWS.guardarAutorResponse guardarAutor(CampusStoreWeb.AutorWS.guardarAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/guardarAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/guardarAutorResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.guardarAutorResponse> guardarAutorAsync(CampusStoreWeb.AutorWS.guardarAutorRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/eliminarAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/eliminarAutorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CampusStoreWeb.AutorWS.eliminarAutorResponse eliminarAutor(CampusStoreWeb.AutorWS.eliminarAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/AutorWS/eliminarAutorRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/AutorWS/eliminarAutorResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.eliminarAutorResponse> eliminarAutorAsync(CampusStoreWeb.AutorWS.eliminarAutorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private string apellidosField;
        
        private int idAutorField;
        
        private bool idAutorFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAutorSpecified {
            get {
                return this.idAutorFieldSpecified;
            }
            set {
                this.idAutorFieldSpecified = value;
                this.RaisePropertyChanged("idAutorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAutor", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerAutorRequest() {
        }
        
        public obtenerAutorRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAutorResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerAutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.AutorWS.autor @return;
        
        public obtenerAutorResponse() {
        }
        
        public obtenerAutorResponse(CampusStoreWeb.AutorWS.autor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutores", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresRequest {
        
        public listarAutoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutoresResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.AutorWS.autor[] @return;
        
        public listarAutoresResponse() {
        }
        
        public listarAutoresResponse(CampusStoreWeb.AutorWS.autor[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarAutor", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.AutorWS.autor autor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.AutorWS.estado estado;
        
        public guardarAutorRequest() {
        }
        
        public guardarAutorRequest(CampusStoreWeb.AutorWS.autor autor, CampusStoreWeb.AutorWS.estado estado) {
            this.autor = autor;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarAutorResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarAutorResponse {
        
        public guardarAutorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAutor", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarAutorRequest() {
        }
        
        public eliminarAutorRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAutorResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarAutorResponse {
        
        public eliminarAutorResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutorWSChannel : CampusStoreWeb.AutorWS.AutorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.AutorWS.AutorWS>, CampusStoreWeb.AutorWS.AutorWS {
        
        public AutorWSClient() {
        }
        
        public AutorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.AutorWS.obtenerAutorResponse CampusStoreWeb.AutorWS.AutorWS.obtenerAutor(CampusStoreWeb.AutorWS.obtenerAutorRequest request) {
            return base.Channel.obtenerAutor(request);
        }
        
        public CampusStoreWeb.AutorWS.autor obtenerAutor(int id) {
            CampusStoreWeb.AutorWS.obtenerAutorRequest inValue = new CampusStoreWeb.AutorWS.obtenerAutorRequest();
            inValue.id = id;
            CampusStoreWeb.AutorWS.obtenerAutorResponse retVal = ((CampusStoreWeb.AutorWS.AutorWS)(this)).obtenerAutor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.obtenerAutorResponse> CampusStoreWeb.AutorWS.AutorWS.obtenerAutorAsync(CampusStoreWeb.AutorWS.obtenerAutorRequest request) {
            return base.Channel.obtenerAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.obtenerAutorResponse> obtenerAutorAsync(int id) {
            CampusStoreWeb.AutorWS.obtenerAutorRequest inValue = new CampusStoreWeb.AutorWS.obtenerAutorRequest();
            inValue.id = id;
            return ((CampusStoreWeb.AutorWS.AutorWS)(this)).obtenerAutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.AutorWS.listarAutoresResponse CampusStoreWeb.AutorWS.AutorWS.listarAutores(CampusStoreWeb.AutorWS.listarAutoresRequest request) {
            return base.Channel.listarAutores(request);
        }
        
        public CampusStoreWeb.AutorWS.autor[] listarAutores() {
            CampusStoreWeb.AutorWS.listarAutoresRequest inValue = new CampusStoreWeb.AutorWS.listarAutoresRequest();
            CampusStoreWeb.AutorWS.listarAutoresResponse retVal = ((CampusStoreWeb.AutorWS.AutorWS)(this)).listarAutores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.listarAutoresResponse> CampusStoreWeb.AutorWS.AutorWS.listarAutoresAsync(CampusStoreWeb.AutorWS.listarAutoresRequest request) {
            return base.Channel.listarAutoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.listarAutoresResponse> listarAutoresAsync() {
            CampusStoreWeb.AutorWS.listarAutoresRequest inValue = new CampusStoreWeb.AutorWS.listarAutoresRequest();
            return ((CampusStoreWeb.AutorWS.AutorWS)(this)).listarAutoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.AutorWS.guardarAutorResponse CampusStoreWeb.AutorWS.AutorWS.guardarAutor(CampusStoreWeb.AutorWS.guardarAutorRequest request) {
            return base.Channel.guardarAutor(request);
        }
        
        public void guardarAutor(CampusStoreWeb.AutorWS.autor autor, CampusStoreWeb.AutorWS.estado estado) {
            CampusStoreWeb.AutorWS.guardarAutorRequest inValue = new CampusStoreWeb.AutorWS.guardarAutorRequest();
            inValue.autor = autor;
            inValue.estado = estado;
            CampusStoreWeb.AutorWS.guardarAutorResponse retVal = ((CampusStoreWeb.AutorWS.AutorWS)(this)).guardarAutor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.guardarAutorResponse> CampusStoreWeb.AutorWS.AutorWS.guardarAutorAsync(CampusStoreWeb.AutorWS.guardarAutorRequest request) {
            return base.Channel.guardarAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.guardarAutorResponse> guardarAutorAsync(CampusStoreWeb.AutorWS.autor autor, CampusStoreWeb.AutorWS.estado estado) {
            CampusStoreWeb.AutorWS.guardarAutorRequest inValue = new CampusStoreWeb.AutorWS.guardarAutorRequest();
            inValue.autor = autor;
            inValue.estado = estado;
            return ((CampusStoreWeb.AutorWS.AutorWS)(this)).guardarAutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.AutorWS.eliminarAutorResponse CampusStoreWeb.AutorWS.AutorWS.eliminarAutor(CampusStoreWeb.AutorWS.eliminarAutorRequest request) {
            return base.Channel.eliminarAutor(request);
        }
        
        public void eliminarAutor(int id) {
            CampusStoreWeb.AutorWS.eliminarAutorRequest inValue = new CampusStoreWeb.AutorWS.eliminarAutorRequest();
            inValue.id = id;
            CampusStoreWeb.AutorWS.eliminarAutorResponse retVal = ((CampusStoreWeb.AutorWS.AutorWS)(this)).eliminarAutor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.eliminarAutorResponse> CampusStoreWeb.AutorWS.AutorWS.eliminarAutorAsync(CampusStoreWeb.AutorWS.eliminarAutorRequest request) {
            return base.Channel.eliminarAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.AutorWS.eliminarAutorResponse> eliminarAutorAsync(int id) {
            CampusStoreWeb.AutorWS.eliminarAutorRequest inValue = new CampusStoreWeb.AutorWS.eliminarAutorRequest();
            inValue.id = id;
            return ((CampusStoreWeb.AutorWS.AutorWS)(this)).eliminarAutorAsync(inValue);
        }
    }
}
