//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusStoreWeb.CarritoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", ConfigurationName="CarritoWS.CarritoWS")]
    public interface CarritoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoPorClienteRequest" +
            "", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoPorClienteRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse obtenerCarritoPorCliente(CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoPorClienteRequest" +
            "", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoPorClienteRespons" +
            "e")]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse> obtenerCarritoPorClienteAsync(CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/listarCarritosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/listarCarritosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.CarritoWS.listarCarritosResponse listarCarritos(CampusStoreWeb.CarritoWS.listarCarritosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/listarCarritosRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/listarCarritosResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.listarCarritosResponse> listarCarritosAsync(CampusStoreWeb.CarritoWS.listarCarritosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CampusStoreWeb.CarritoWS.obtenerCarritoResponse obtenerCarrito(CampusStoreWeb.CarritoWS.obtenerCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/obtenerCarritoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoResponse> obtenerCarritoAsync(CampusStoreWeb.CarritoWS.obtenerCarritoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/eliminarCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/eliminarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CampusStoreWeb.CarritoWS.eliminarCarritoResponse eliminarCarrito(CampusStoreWeb.CarritoWS.eliminarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/eliminarCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/eliminarCarritoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.eliminarCarritoResponse> eliminarCarritoAsync(CampusStoreWeb.CarritoWS.eliminarCarritoRequest request);
        
        // CODEGEN: Parameter 'carrito' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/guardarCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/guardarCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        CampusStoreWeb.CarritoWS.guardarCarritoResponse guardarCarrito(CampusStoreWeb.CarritoWS.guardarCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.campusstore.pucp.edu.pe/CarritoWS/guardarCarritoRequest", ReplyAction="http://services.campusstore.pucp.edu.pe/CarritoWS/guardarCarritoResponse")]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.guardarCarritoResponse> guardarCarritoAsync(CampusStoreWeb.CarritoWS.guardarCarritoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class carrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private bool completadoField;
        
        private bool completadoFieldSpecified;
        
        private cupon cuponField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private int idCarritoField;
        
        private bool idCarritoFieldSpecified;
        
        private lineaCarrito[] lineasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool completado {
            get {
                return this.completadoField;
            }
            set {
                this.completadoField = value;
                this.RaisePropertyChanged("completado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completadoSpecified {
            get {
                return this.completadoFieldSpecified;
            }
            set {
                this.completadoFieldSpecified = value;
                this.RaisePropertyChanged("completadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cupon cupon {
            get {
                return this.cuponField;
            }
            set {
                this.cuponField = value;
                this.RaisePropertyChanged("cupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                this.idCarritoField = value;
                this.RaisePropertyChanged("idCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCarritoSpecified {
            get {
                return this.idCarritoFieldSpecified;
            }
            set {
                this.idCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lineaCarrito[] lineas {
            get {
                return this.lineasField;
            }
            set {
                this.lineasField = value;
                this.RaisePropertyChanged("lineas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cliente : usuario {
        
        private cupon[] cuponesUsadosField;
        
        private int idClienteField;
        
        private bool idClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuponesUsados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public cupon[] cuponesUsados {
            get {
                return this.cuponesUsadosField;
            }
            set {
                this.cuponesUsadosField = value;
                this.RaisePropertyChanged("cuponesUsados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idClienteSpecified {
            get {
                return this.idClienteFieldSpecified;
            }
            set {
                this.idClienteFieldSpecified = value;
                this.RaisePropertyChanged("idClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class cupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private string codigoField;
        
        private double descuentoField;
        
        private bool descuentoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idCuponField;
        
        private bool idCuponFieldSpecified;
        
        private int usosRestantesField;
        
        private bool usosRestantesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoSpecified {
            get {
                return this.descuentoFieldSpecified;
            }
            set {
                this.descuentoFieldSpecified = value;
                this.RaisePropertyChanged("descuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCupon {
            get {
                return this.idCuponField;
            }
            set {
                this.idCuponField = value;
                this.RaisePropertyChanged("idCupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCuponSpecified {
            get {
                return this.idCuponFieldSpecified;
            }
            set {
                this.idCuponFieldSpecified = value;
                this.RaisePropertyChanged("idCuponSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int usosRestantes {
            get {
                return this.usosRestantesField;
            }
            set {
                this.usosRestantesField = value;
                this.RaisePropertyChanged("usosRestantes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usosRestantesSpecified {
            get {
                return this.usosRestantesFieldSpecified;
            }
            set {
                this.usosRestantesFieldSpecified = value;
                this.RaisePropertyChanged("usosRestantesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasField;
        
        private string apellidosField;
        
        private int idAutorField;
        
        private bool idAutorFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAutorSpecified {
            get {
                return this.idAutorFieldSpecified;
            }
            set {
                this.idAutorFieldSpecified = value;
                this.RaisePropertyChanged("idAutorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class editorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cifField;
        
        private string direccionField;
        
        private string emailField;
        
        private int idEditorialField;
        
        private bool idEditorialFieldSpecified;
        
        private string nombreField;
        
        private string sitioWebField;
        
        private int telefonoField;
        
        private bool telefonoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cif {
            get {
                return this.cifField;
            }
            set {
                this.cifField = value;
                this.RaisePropertyChanged("cif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEditorialSpecified {
            get {
                return this.idEditorialFieldSpecified;
            }
            set {
                this.idEditorialFieldSpecified = value;
                this.RaisePropertyChanged("idEditorialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sitioWeb {
            get {
                return this.sitioWebField;
            }
            set {
                this.sitioWebField = value;
                this.RaisePropertyChanged("sitioWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telefonoSpecified {
            get {
                return this.telefonoFieldSpecified;
            }
            set {
                this.telefonoFieldSpecified = value;
                this.RaisePropertyChanged("telefonoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class reseña : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double calificacionField;
        
        private cliente clienteField;
        
        private int idReseñaField;
        
        private bool idReseñaFieldSpecified;
        
        private producto productoField;
        
        private string reseña1Field;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double calificacion {
            get {
                return this.calificacionField;
            }
            set {
                this.calificacionField = value;
                this.RaisePropertyChanged("calificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idReseña {
            get {
                return this.idReseñaField;
            }
            set {
                this.idReseñaField = value;
                this.RaisePropertyChanged("idReseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idReseñaSpecified {
            get {
                return this.idReseñaFieldSpecified;
            }
            set {
                this.idReseñaFieldSpecified = value;
                this.RaisePropertyChanged("idReseñaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseña", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reseña1 {
            get {
                return this.reseña1Field;
            }
            set {
                this.reseña1Field = value;
                this.RaisePropertyChanged("reseña1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(articulo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(libro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private double precioDescuentoField;
        
        private bool precioDescuentoFieldSpecified;
        
        private int stockRealField;
        
        private bool stockRealFieldSpecified;
        
        private int stockVirtualField;
        
        private bool stockVirtualFieldSpecified;
        
        private string nombreField;
        
        private string descripcionField;
        
        private descuento descuentoField;
        
        private reseña[] reseñasField;
        
        private string imagenURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double precioDescuento {
            get {
                return this.precioDescuentoField;
            }
            set {
                this.precioDescuentoField = value;
                this.RaisePropertyChanged("precioDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioDescuentoSpecified {
            get {
                return this.precioDescuentoFieldSpecified;
            }
            set {
                this.precioDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("precioDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stockReal {
            get {
                return this.stockRealField;
            }
            set {
                this.stockRealField = value;
                this.RaisePropertyChanged("stockReal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockRealSpecified {
            get {
                return this.stockRealFieldSpecified;
            }
            set {
                this.stockRealFieldSpecified = value;
                this.RaisePropertyChanged("stockRealSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stockVirtual {
            get {
                return this.stockVirtualField;
            }
            set {
                this.stockVirtualField = value;
                this.RaisePropertyChanged("stockVirtual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockVirtualSpecified {
            get {
                return this.stockVirtualFieldSpecified;
            }
            set {
                this.stockVirtualFieldSpecified = value;
                this.RaisePropertyChanged("stockVirtualSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public descuento descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reseñas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public reseña[] reseñas {
            get {
                return this.reseñasField;
            }
            set {
                this.reseñasField = value;
                this.RaisePropertyChanged("reseñas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string imagenURL {
            get {
                return this.imagenURLField;
            }
            set {
                this.imagenURLField = value;
                this.RaisePropertyChanged("imagenURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class descuento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private System.DateTime fechaCaducidadField;
        
        private bool fechaCaducidadFieldSpecified;
        
        private int idDescuentoField;
        
        private bool idDescuentoFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        private double valorDescuentoField;
        
        private bool valorDescuentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaCaducidad {
            get {
                return this.fechaCaducidadField;
            }
            set {
                this.fechaCaducidadField = value;
                this.RaisePropertyChanged("fechaCaducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCaducidadSpecified {
            get {
                return this.fechaCaducidadFieldSpecified;
            }
            set {
                this.fechaCaducidadFieldSpecified = value;
                this.RaisePropertyChanged("fechaCaducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDescuento {
            get {
                return this.idDescuentoField;
            }
            set {
                this.idDescuentoField = value;
                this.RaisePropertyChanged("idDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDescuentoSpecified {
            get {
                return this.idDescuentoFieldSpecified;
            }
            set {
                this.idDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("idDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double valorDescuento {
            get {
                return this.valorDescuentoField;
            }
            set {
                this.valorDescuentoField = value;
                this.RaisePropertyChanged("valorDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorDescuentoSpecified {
            get {
                return this.valorDescuentoFieldSpecified;
            }
            set {
                this.valorDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("valorDescuentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoProducto {
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        LIBRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class articulo : producto {
        
        private int idArticuloField;
        
        private bool idArticuloFieldSpecified;
        
        private tipoArticulo tipoArticuloField;
        
        private bool tipoArticuloFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
                this.RaisePropertyChanged("idArticulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idArticuloSpecified {
            get {
                return this.idArticuloFieldSpecified;
            }
            set {
                this.idArticuloFieldSpecified = value;
                this.RaisePropertyChanged("idArticuloSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoArticulo tipoArticulo {
            get {
                return this.tipoArticuloField;
            }
            set {
                this.tipoArticuloField = value;
                this.RaisePropertyChanged("tipoArticulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoArticuloSpecified {
            get {
                return this.tipoArticuloFieldSpecified;
            }
            set {
                this.tipoArticuloFieldSpecified = value;
                this.RaisePropertyChanged("tipoArticuloSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum tipoArticulo {
        
        /// <remarks/>
        LAPICERO,
        
        /// <remarks/>
        CUADERNO,
        
        /// <remarks/>
        PELUCHE,
        
        /// <remarks/>
        TOMATODO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class libro : producto {
        
        private int idLibroField;
        
        private bool idLibroFieldSpecified;
        
        private string isbnField;
        
        private generoLibro generoField;
        
        private bool generoFieldSpecified;
        
        private System.DateTime fechaPublicacionField;
        
        private bool fechaPublicacionFieldSpecified;
        
        private formato formatoField;
        
        private bool formatoFieldSpecified;
        
        private string sinopsisField;
        
        private editorial editorialField;
        
        private autor[] autoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idLibro {
            get {
                return this.idLibroField;
            }
            set {
                this.idLibroField = value;
                this.RaisePropertyChanged("idLibro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLibroSpecified {
            get {
                return this.idLibroFieldSpecified;
            }
            set {
                this.idLibroFieldSpecified = value;
                this.RaisePropertyChanged("idLibroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public generoLibro genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("fechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPublicacionSpecified {
            get {
                return this.fechaPublicacionFieldSpecified;
            }
            set {
                this.fechaPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public formato formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
                this.RaisePropertyChanged("formato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatoSpecified {
            get {
                return this.formatoFieldSpecified;
            }
            set {
                this.formatoFieldSpecified = value;
                this.RaisePropertyChanged("formatoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                this.sinopsisField = value;
                this.RaisePropertyChanged("sinopsis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public editorial editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("autores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public autor[] autores {
            get {
                return this.autoresField;
            }
            set {
                this.autoresField = value;
                this.RaisePropertyChanged("autores");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum generoLibro {
        
        /// <remarks/>
        DRAMA,
        
        /// <remarks/>
        FANTASIA,
        
        /// <remarks/>
        NOVELA,
        
        /// <remarks/>
        NARRATIVO,
        
        /// <remarks/>
        AVENTURA,
        
        /// <remarks/>
        CIENCIA_FICCION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum formato {
        
        /// <remarks/>
        TAPA_BLANDA,
        
        /// <remarks/>
        TAPA_DURA,
        
        /// <remarks/>
        COLECCIONISTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public partial class lineaCarrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private carrito carritoField;
        
        private int idLineaCarritoField;
        
        private bool idLineaCarritoFieldSpecified;
        
        private double precioConDescuentoField;
        
        private bool precioConDescuentoFieldSpecified;
        
        private double precioUnitarioField;
        
        private bool precioUnitarioFieldSpecified;
        
        private producto productoField;
        
        private double subTotalConDescuentoField;
        
        private bool subTotalConDescuentoFieldSpecified;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private tipoProducto tipoProductoField;
        
        private bool tipoProductoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public carrito carrito {
            get {
                return this.carritoField;
            }
            set {
                this.carritoField = value;
                this.RaisePropertyChanged("carrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idLineaCarrito {
            get {
                return this.idLineaCarritoField;
            }
            set {
                this.idLineaCarritoField = value;
                this.RaisePropertyChanged("idLineaCarrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLineaCarritoSpecified {
            get {
                return this.idLineaCarritoFieldSpecified;
            }
            set {
                this.idLineaCarritoFieldSpecified = value;
                this.RaisePropertyChanged("idLineaCarritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioConDescuento {
            get {
                return this.precioConDescuentoField;
            }
            set {
                this.precioConDescuentoField = value;
                this.RaisePropertyChanged("precioConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioConDescuentoSpecified {
            get {
                return this.precioConDescuentoFieldSpecified;
            }
            set {
                this.precioConDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("precioConDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioUnitarioSpecified {
            get {
                return this.precioUnitarioFieldSpecified;
            }
            set {
                this.precioUnitarioFieldSpecified = value;
                this.RaisePropertyChanged("precioUnitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double subTotalConDescuento {
            get {
                return this.subTotalConDescuentoField;
            }
            set {
                this.subTotalConDescuentoField = value;
                this.RaisePropertyChanged("subTotalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalConDescuentoSpecified {
            get {
                return this.subTotalConDescuentoFieldSpecified;
            }
            set {
                this.subTotalConDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("subTotalConDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoProducto tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                this.tipoProductoField = value;
                this.RaisePropertyChanged("tipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoProductoSpecified {
            get {
                return this.tipoProductoFieldSpecified;
            }
            set {
                this.tipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("tipoProductoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public abstract partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contraseñaField;
        
        private string correoField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoPorCliente", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoPorClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerCarritoPorClienteRequest() {
        }
        
        public obtenerCarritoPorClienteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoPorClienteResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoPorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.CarritoWS.carrito @return;
        
        public obtenerCarritoPorClienteResponse() {
        }
        
        public obtenerCarritoPorClienteResponse(CampusStoreWeb.CarritoWS.carrito @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCarritos", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCarritosRequest {
        
        public listarCarritosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCarritosResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCarritosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.CarritoWS.carrito[] @return;
        
        public listarCarritosResponse() {
        }
        
        public listarCarritosResponse(CampusStoreWeb.CarritoWS.carrito[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarrito", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerCarritoRequest() {
        }
        
        public obtenerCarritoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.CarritoWS.carrito @return;
        
        public obtenerCarritoResponse() {
        }
        
        public obtenerCarritoResponse(CampusStoreWeb.CarritoWS.carrito @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarrito", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarCarritoRequest() {
        }
        
        public eliminarCarritoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoResponse {
        
        public eliminarCarritoResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.campusstore.pucp.edu.pe/")]
    public enum estado {
        
        /// <remarks/>
        Nuevo,
        
        /// <remarks/>
        Modificado,
        
        /// <remarks/>
        Eliminado,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarCarrito", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.CarritoWS.carrito carrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.campusstore.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampusStoreWeb.CarritoWS.estado estado;
        
        public guardarCarritoRequest() {
        }
        
        public guardarCarritoRequest(CampusStoreWeb.CarritoWS.carrito carrito, CampusStoreWeb.CarritoWS.estado estado) {
            this.carrito = carrito;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="guardarCarritoResponse", WrapperNamespace="http://services.campusstore.pucp.edu.pe/", IsWrapped=true)]
    public partial class guardarCarritoResponse {
        
        public guardarCarritoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarritoWSChannel : CampusStoreWeb.CarritoWS.CarritoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarritoWSClient : System.ServiceModel.ClientBase<CampusStoreWeb.CarritoWS.CarritoWS>, CampusStoreWeb.CarritoWS.CarritoWS {
        
        public CarritoWSClient() {
        }
        
        public CarritoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarritoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse CampusStoreWeb.CarritoWS.CarritoWS.obtenerCarritoPorCliente(CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest request) {
            return base.Channel.obtenerCarritoPorCliente(request);
        }
        
        public CampusStoreWeb.CarritoWS.carrito obtenerCarritoPorCliente(int id) {
            CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest inValue = new CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest();
            inValue.id = id;
            CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse retVal = ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).obtenerCarritoPorCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse> CampusStoreWeb.CarritoWS.CarritoWS.obtenerCarritoPorClienteAsync(CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest request) {
            return base.Channel.obtenerCarritoPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteResponse> obtenerCarritoPorClienteAsync(int id) {
            CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest inValue = new CampusStoreWeb.CarritoWS.obtenerCarritoPorClienteRequest();
            inValue.id = id;
            return ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).obtenerCarritoPorClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.CarritoWS.listarCarritosResponse CampusStoreWeb.CarritoWS.CarritoWS.listarCarritos(CampusStoreWeb.CarritoWS.listarCarritosRequest request) {
            return base.Channel.listarCarritos(request);
        }
        
        public CampusStoreWeb.CarritoWS.carrito[] listarCarritos() {
            CampusStoreWeb.CarritoWS.listarCarritosRequest inValue = new CampusStoreWeb.CarritoWS.listarCarritosRequest();
            CampusStoreWeb.CarritoWS.listarCarritosResponse retVal = ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).listarCarritos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.listarCarritosResponse> CampusStoreWeb.CarritoWS.CarritoWS.listarCarritosAsync(CampusStoreWeb.CarritoWS.listarCarritosRequest request) {
            return base.Channel.listarCarritosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.listarCarritosResponse> listarCarritosAsync() {
            CampusStoreWeb.CarritoWS.listarCarritosRequest inValue = new CampusStoreWeb.CarritoWS.listarCarritosRequest();
            return ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).listarCarritosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.CarritoWS.obtenerCarritoResponse CampusStoreWeb.CarritoWS.CarritoWS.obtenerCarrito(CampusStoreWeb.CarritoWS.obtenerCarritoRequest request) {
            return base.Channel.obtenerCarrito(request);
        }
        
        public CampusStoreWeb.CarritoWS.carrito obtenerCarrito(int id) {
            CampusStoreWeb.CarritoWS.obtenerCarritoRequest inValue = new CampusStoreWeb.CarritoWS.obtenerCarritoRequest();
            inValue.id = id;
            CampusStoreWeb.CarritoWS.obtenerCarritoResponse retVal = ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).obtenerCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoResponse> CampusStoreWeb.CarritoWS.CarritoWS.obtenerCarritoAsync(CampusStoreWeb.CarritoWS.obtenerCarritoRequest request) {
            return base.Channel.obtenerCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.obtenerCarritoResponse> obtenerCarritoAsync(int id) {
            CampusStoreWeb.CarritoWS.obtenerCarritoRequest inValue = new CampusStoreWeb.CarritoWS.obtenerCarritoRequest();
            inValue.id = id;
            return ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).obtenerCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.CarritoWS.eliminarCarritoResponse CampusStoreWeb.CarritoWS.CarritoWS.eliminarCarrito(CampusStoreWeb.CarritoWS.eliminarCarritoRequest request) {
            return base.Channel.eliminarCarrito(request);
        }
        
        public void eliminarCarrito(int id) {
            CampusStoreWeb.CarritoWS.eliminarCarritoRequest inValue = new CampusStoreWeb.CarritoWS.eliminarCarritoRequest();
            inValue.id = id;
            CampusStoreWeb.CarritoWS.eliminarCarritoResponse retVal = ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).eliminarCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.eliminarCarritoResponse> CampusStoreWeb.CarritoWS.CarritoWS.eliminarCarritoAsync(CampusStoreWeb.CarritoWS.eliminarCarritoRequest request) {
            return base.Channel.eliminarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.eliminarCarritoResponse> eliminarCarritoAsync(int id) {
            CampusStoreWeb.CarritoWS.eliminarCarritoRequest inValue = new CampusStoreWeb.CarritoWS.eliminarCarritoRequest();
            inValue.id = id;
            return ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).eliminarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CampusStoreWeb.CarritoWS.guardarCarritoResponse CampusStoreWeb.CarritoWS.CarritoWS.guardarCarrito(CampusStoreWeb.CarritoWS.guardarCarritoRequest request) {
            return base.Channel.guardarCarrito(request);
        }
        
        public void guardarCarrito(CampusStoreWeb.CarritoWS.carrito carrito, CampusStoreWeb.CarritoWS.estado estado) {
            CampusStoreWeb.CarritoWS.guardarCarritoRequest inValue = new CampusStoreWeb.CarritoWS.guardarCarritoRequest();
            inValue.carrito = carrito;
            inValue.estado = estado;
            CampusStoreWeb.CarritoWS.guardarCarritoResponse retVal = ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).guardarCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.guardarCarritoResponse> CampusStoreWeb.CarritoWS.CarritoWS.guardarCarritoAsync(CampusStoreWeb.CarritoWS.guardarCarritoRequest request) {
            return base.Channel.guardarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CampusStoreWeb.CarritoWS.guardarCarritoResponse> guardarCarritoAsync(CampusStoreWeb.CarritoWS.carrito carrito, CampusStoreWeb.CarritoWS.estado estado) {
            CampusStoreWeb.CarritoWS.guardarCarritoRequest inValue = new CampusStoreWeb.CarritoWS.guardarCarritoRequest();
            inValue.carrito = carrito;
            inValue.estado = estado;
            return ((CampusStoreWeb.CarritoWS.CarritoWS)(this)).guardarCarritoAsync(inValue);
        }
    }
}
